# === CDSE DOWNLOADER CONFIGURATION ===

# CDSE Kullanıcı Bilgileri
CDSE_USERNAME: "javodix397@kimdyn.com"
CDSE_PASSWORD: "Asddsa.12345"

# Dosya Yolları
OUTPUT_PATH: "./downloads"
EXTRACT_PATH: "./extracted"

# Sentinel Ayarları
COLLECTION_NAME: "SENTINEL-2"
PRODUCT_TYPE: "S2MSI2A"

# Grid Kodları (Sentinel-2 için)
GRID_CODE:

# Maksimum Bulut Örtüsü (%)
CLOUDCOVER_MAX: 20

# Tarih Ayarları
DATE_AUTO: true
DATE_AUTO_RANGE: 20
START_DATE: "2025-07-28"
END_DATE: "2025-07-30"

# API Ayarları
MAX_PRODUCTS: 10
